# Generated by Django 6.0.6 on 2026-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='पूरा नाम')),
                ('phone', models.CharField(max_length=15, verbose_name='फ़ोन नंबर')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ईमेल')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='गोरखपुर का इलाका')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
