# Generated by Django 6.0.6 on 2026-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_service_type_alter_lead_area_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
