# Generated by Django 6.0.6 on 2026-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='amount_paid_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='कुल तय रकम', max_digits=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='इंजीनियर या वर्कर का नाम', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.CharField(choices=[('new', 'New Lead'), ('assigned', 'Engineer Assigned'), ('in_progress', 'Work In Progress'), ('completed', 'Work Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_review',
            field=models.TextField(blank=True, help_text='काम पूरा होने के बाद कस्टमर का फीडबैक', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='engineer_status',
            field=models.CharField(blank=True, help_text='जैसे: On the way, Reached, Delayed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(blank=True, help_text='1 से 5 स्टार रेटिंग', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
