# Generated by Django 6.0.6 on 2026-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_amount_paid_status_lead_amount_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.CharField(blank=True, choices=[('Ravi Kumar', 'रवि कुमार (Plumbing)'), ('Amit Sharma', 'अमित शर्मा (Electrical)'), ('Vikash Prajapati', 'विकाश प्रजापति (Electronics)'), ('Sandeep Yadav', 'संदीप यादव (Home Appliances)')], help_text='लीड के लिए वर्कर या इंजीनियर चुनें', max_length=100, null=True),
        ),
    ]
