# Generated by Django 6.0.6 on 2026-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='घर का पूरा पता'),
        ),
    ]
