"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yg5%u54ksvk!6$+h@pr0*@f%lwab&lq&(2=dg^@)l%ck!_t)fx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 1. ALLOWED_HOSTS - नए और पुराने सभी डोमेन्स को अनुमति दें
ALLOWED_HOSTS = [
    'fixmyhome-a4r4.onrender.com',  # रेंडर का पुराना यूआरएल
    'fixmyhomes.in',                # आपका नया बिना www का मुख्य डोमेन
    'www.fixmyhomes.in',            # आपका www वाला डोमेन
    '127.0.0.1', 
    'localhost'
]

# 2. 🎯 CSRF TRUSTED ORIGINS - (403 एरर को ठीक करने के लिए सबसे महत्वपूर्ण क्लीन लिस्ट)
CSRF_TRUSTED_ORIGINS = [
    'https://fixmyhomes.in',
    'https://www.fixmyhomes.in',
    'https://fixmyhome-a4r4.onrender.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # 🎯 गूगल रैंकिंग के लिए साइटमैप ऐप जोड़ा गया
    'leads'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database Configuration
# 🎯 यहाँ हमने रेंडर के पुराने डेटाबेस को हटाकर आपके नए Neon.tech फ्री डेटाबेस को जोड़ दिया है!
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://neondb_owner:npg_2bJiQWkrNCt5@ep-autumn-sunset-atbr3jex.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require',
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# सुपरयूज़र क्रेडेंशियल्स एन्वायरमेंट सेटिंग्स
os.environ["DJANGO_SUPERUSER_PASSWORD"] = "Sunil@1234"